name: Triton-ascend

on:
  push:
    branches:
      - main
      - triton
  pull_request:
    branches:
      - main
      - triton
  workflow_dispatch:
    inputs:
        runner:
          required: true
          type: choice
          options:
            - self-hosted
            - linux-arm64-npu-1
            - linux-arm64-npu-2
            - linux-arm64-npu-4
          default: 'linux-arm64-npu-1'
          description: 'Runner to run on'

env:
  PYTHON: python3
  PIP_DISABLE_PIP_VERSION_CHECK: "1"

jobs:
  build-llvm:
    name: Build · Test · Package
    runs-on: ${{ inputs.runner || 'linux-arm64-npu-1' }}
    container: 
      image: swr.cn-southwest-2.myhuaweicloud.com/base_image/ascend-ci/cann:8.3.rc1-910b-ubuntu22.04-py3.11
      env:
        HF_ENDPOINT: https://hf-mirror.com
      options: --user root
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
      - name: Show NPU info
        run: |
          npu-smi info

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Config mirrors
        run: |
          sed -i 's|ports.ubuntu.com|mirrors.tuna.tsinghua.edu.cn|g' /etc/apt/sources.list
          pip config set global.index-url https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple

     steps:
      - name: Install Build Deps
        run: |
          sudo apt-get update
          sudo apt-get install -y clang lld ninja-build
      
      - name: Build and Package LLVM
        run: make build-llvm 
        
      - name: Cache LLVM Tarball
        uses: actions/cache@v4
        with:
          path: llvm-*.tar.gz
          key: llvm-${{ hashFiles('llvm-hash.txt') }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Build Triton Wheel
        run: |
          make install-dev-reqs
          make package PYTHON=python${{ matrix.python-version }}
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: triton-wheel-${{ matrix.python-version }}
          path: dist/*.whl

  # docker-publish:
  #   if: github.event_name == 'push'
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Login to Quay.io
  #       uses: docker/login-action@v3
  #       with:
  #         registry: quay.io
  #         username: ${{ secrets.QUAY_USER }}
  #         password: ${{ secrets.QUAY_PASSWD }}
          
  #     - name: Build and Push Docker Image
  #       run: make image_build